#!/bin/bash
for _ in $(seq 1 30); do
  current_size=$(xrandr 2>/dev/null | awk '/ connected/ { for (i = 1; i <= NF; i++) if ($i ~ /^[0-9]+x[0-9]+\+/) { split($i, size, "+"); print size[1]; exit } }')
  if [ -n "$current_size" ] && [ "$current_size" != "1024x768" ]; then
    break
  fi
  sleep 1
done

exec OpenAudible
