services:
  openaudible:
    image: ghcr.io/hypnotoad08/openaudible-docker:main
    container_name: openaudible
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - CUSTOM_USER=JohnDoe # optional, but recommended if exposing to -
      - PASSWORD=a-safe-pw  # the internet without any other form of authentication
    ports:
      - "3000:3000" #http
      - "3001:3001" #https
    volumes:
      - /path/to/config:/config
      # Optional: mount trusted certs for HTTPS. Directory must contain cert.pem and cert.key.
      # - /path/to/certs:/config/ssl:ro
    restart: unless-stopped
